"""empty message

Revision ID: 215e9338dfbf
Revises: 664863f8d63a
Create Date: 2024-01-13 11:55:18.620257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215e9338dfbf'
down_revision = '664863f8d63a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_credit_card_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_credit_card_info',
    sa.Column('credit_card_number', sa.VARCHAR(), nullable=False),
    sa.Column('name_on_card', sa.VARCHAR(), nullable=True),
    sa.Column('expiration_date', sa.VARCHAR(), nullable=True),
    sa.Column('cvv', sa.VARCHAR(), nullable=True),
    sa.Column('street_address', sa.VARCHAR(), nullable=True),
    sa.Column('country', sa.VARCHAR(), nullable=True),
    sa.Column('zipcode', sa.VARCHAR(), nullable=True),
    sa.Column('city', sa.VARCHAR(), nullable=True),
    sa.Column('state', sa.VARCHAR(), nullable=True),
    sa.Column('save_my_card', sa.BOOLEAN(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_credit_card_info_user_id_user'),
    sa.PrimaryKeyConstraint('credit_card_number', name='pk_credit_card_info'),
    sa.UniqueConstraint('credit_card_number', name='uq_credit_card_info_credit_card_number')
    )
    # ### end Alembic commands ###
