"""empty message

Revision ID: 28d7ccd6b920
Revises: d7f380f4d91c
Create Date: 2024-01-13 11:50:00.734522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28d7ccd6b920'
down_revision = 'd7f380f4d91c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card_info', schema=None) as batch_op:
        batch_op.alter_column('credit_card_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.alter_column('credit_card_number',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
