"""empty message

Revision ID: 3ceae1172fb7
Revises: e1943c0bb61d
Create Date: 2024-01-13 11:42:38.247867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ceae1172fb7'
down_revision = 'e1943c0bb61d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('race_name', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_event', schema=None) as batch_op:
        batch_op.drop_column('race_name')

    # ### end Alembic commands ###
