"""added start_time to race_event

Revision ID: 421435a6e7c3
Revises: ba1e21d898ee
Create Date: 2024-02-10 10:19:03.543759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '421435a6e7c3'
down_revision = 'ba1e21d898ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('start_day', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('packetpickup_day', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('packetpickup_location', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_event', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('packetpickup_location')
        batch_op.drop_column('packetpickup_day')
        batch_op.drop_column('start_day')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
