"""Add race types and prices

Revision ID: 4d6f9ae35ca0
Revises: 58f65586892d
Create Date: 2024-02-03 18:54:51.653859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d6f9ae35ca0'
down_revision = '58f65586892d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('race_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_type', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('race_event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['race_event_id'], ['race_event.id'], name=op.f('fk_race_type_race_event_id_race_event')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_race_type'))
    )
    with op.batch_alter_table('race_event', schema=None) as batch_op:
        batch_op.drop_column('price_half')
        batch_op.drop_column('price_5k')
        batch_op.drop_column('price_10k')
        batch_op.drop_column('price_full')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_full', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('price_10k', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('price_5k', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('price_half', sa.FLOAT(), nullable=True))

    op.drop_table('race_type')
    # ### end Alembic commands ###
