"""empty message

Revision ID: 584d6c6f9e51
Revises: 5e8be6936335
Create Date: 2024-01-14 14:06:31.629297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '584d6c6f9e51'
down_revision = '5e8be6936335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card_info', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_credit_card_info_credit_card_number'), ['credit_card_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card_info', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_credit_card_info_credit_card_number'), type_='unique')

    # ### end Alembic commands ###
