"""add price for each race

Revision ID: 58f65586892d
Revises: 59537a22995a
Create Date: 2024-02-03 18:35:41.490356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58f65586892d'
down_revision = '59537a22995a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_5k', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('price_10k', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('price_half', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('price_full', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_event', schema=None) as batch_op:
        batch_op.drop_column('price_full')
        batch_op.drop_column('price_half')
        batch_op.drop_column('price_10k')
        batch_op.drop_column('price_5k')

    # ### end Alembic commands ###
