"""add admin column to user

Revision ID: 59537a22995a
Revises: 3c98b33426ba
Create Date: 2024-01-28 19:24:27.487041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59537a22995a'
down_revision = '3c98b33426ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('admin')

    # ### end Alembic commands ###
