"""empty message

Revision ID: 5e8be6936335
Revises: 215e9338dfbf
Create Date: 2024-01-14 14:02:37.385953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e8be6936335'
down_revision = '215e9338dfbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card_info', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
