"""empty message

Revision ID: 664863f8d63a
Revises: 28d7ccd6b920
Create Date: 2024-01-13 11:52:32.060090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '664863f8d63a'
down_revision = '28d7ccd6b920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_credit_card_info_credit_card_number'), ['credit_card_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card_info', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_credit_card_info_credit_card_number'), type_='unique')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
