"""revise User model for password_hash

Revision ID: 7a261683e5b5
Revises: edcb4532d0a8
Create Date: 2024-02-17 13:02:31.187581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a261683e5b5'
down_revision = 'edcb4532d0a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('admin',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('admin',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
