"""ship_packet to racesignups

Revision ID: 7c02abea6af6
Revises: af0f0a6672e1
Create Date: 2024-02-11 14:48:31.758367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c02abea6af6'
down_revision = 'af0f0a6672e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_signup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ship_packet', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_signup', schema=None) as batch_op:
        batch_op.drop_column('ship_packet')

    # ### end Alembic commands ###
