"""empty message

Revision ID: 9ea8e17469aa
Revises: c1c8528150a4
Create Date: 2024-01-12 12:34:42.154930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ea8e17469aa'
down_revision = 'c1c8528150a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email'))
    )
    op.create_table('credit_card_info',
    sa.Column('credit_card_number', sa.String(), nullable=False),
    sa.Column('name_on_card', sa.String(), nullable=True),
    sa.Column('expiration_date', sa.String(), nullable=True),
    sa.Column('cvv', sa.String(), nullable=True),
    sa.Column('street_address', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('zipcode', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('save_my_card', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_credit_card_info_user_id_user')),
    sa.PrimaryKeyConstraint('credit_card_number', name=op.f('pk_credit_card_info'))
    )
    op.create_table('race_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('race_type', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_race_event_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_race_event'))
    )
    op.create_table('race_signup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('waiver_accept', sa.Boolean(), nullable=True),
    sa.Column('tshirt_size', sa.String(), nullable=True),
    sa.Column('coupon_code', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('race_event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['race_event_id'], ['race_event.id'], name=op.f('fk_race_signup_race_event_id_race_event')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_race_signup_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_race_signup')),
    sa.UniqueConstraint('user_id', name=op.f('uq_race_signup_user_id'))
    )
    op.drop_table('poms')
    op.drop_table('pomads')
    op.drop_table('adoption_requests')
    op.drop_table('users')
    op.drop_table('pets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_pets')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('address_line1', sa.VARCHAR(), nullable=True),
    sa.Column('address_line2', sa.VARCHAR(), nullable=True),
    sa.Column('city', sa.VARCHAR(), nullable=True),
    sa.Column('state', sa.VARCHAR(), nullable=True),
    sa.Column('postal_code', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email'),
    sa.UniqueConstraint('username', name='uq_users_username')
    )
    op.create_table('adoption_requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('pom_id', sa.INTEGER(), nullable=False),
    sa.Column('adopter_name', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['pom_id'], ['poms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pomads',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('pom_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['pom_id'], ['poms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poms',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('color', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('race_signup')
    op.drop_table('race_event')
    op.drop_table('credit_card_info')
    op.drop_table('user')
    # ### end Alembic commands ###
