"""edit estimated_time for user.py

Revision ID: af0f0a6672e1
Revises: 421435a6e7c3
Create Date: 2024-02-10 15:31:10.582588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af0f0a6672e1'
down_revision = '421435a6e7c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_finish_time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('estimated_finish_time')

    # ### end Alembic commands ###
