"""revert back to events, no types

Revision ID: ba1e21d898ee
Revises: 4d6f9ae35ca0
Create Date: 2024-02-09 09:45:53.333242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba1e21d898ee'
down_revision = '4d6f9ae35ca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('race_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('race_type',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('race_type', sa.VARCHAR(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('race_event_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['race_event_id'], ['race_event.id'], name='fk_race_type_race_event_id_race_event'),
    sa.PrimaryKeyConstraint('id', name='pk_race_type')
    )
    # ### end Alembic commands ###
