"""Initial migration

Revision ID: cffaeed539e8
Revises: 
Create Date: 2024-03-07 10:22:24.253318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cffaeed539e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('race_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_name', sa.String(), nullable=False),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('race_type', sa.String(), nullable=True),
    sa.Column('start_time', sa.String(), nullable=True),
    sa.Column('start_day', sa.String(), nullable=True),
    sa.Column('packetpickup_day', sa.String(), nullable=True),
    sa.Column('packetpickup_location', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('race_cost', sa.Float(), nullable=False),
    sa.Column('ratings', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_race_events'))
    )
    op.create_table('shopping_carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_cost', sa.Float(), nullable=True),
    sa.Column('ship_packet_cost', sa.Float(), nullable=True),
    sa.Column('cart_items', sa.Integer(), nullable=True),
    sa.Column('tshirt_size', sa.String(), nullable=True),
    sa.Column('coupon_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shopping_carts'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('estimated_finish_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('credit_card_infos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_card_number', sa.String(), nullable=False),
    sa.Column('name_on_card', sa.String(), nullable=True),
    sa.Column('expiration_date', sa.String(), nullable=True),
    sa.Column('cvv', sa.String(), nullable=True),
    sa.Column('street_address', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('zipcode', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('save_my_card', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_credit_card_infos_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_card_infos')),
    sa.UniqueConstraint('credit_card_number', name=op.f('uq_credit_card_infos_credit_card_number'))
    )
    op.create_table('race_signups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('race_event_id', sa.Integer(), nullable=False),
    sa.Column('waiver_accept', sa.Boolean(), nullable=False),
    sa.Column('tshirt_size', sa.String(), nullable=False),
    sa.Column('coupon_code', sa.String(), nullable=True),
    sa.Column('ship_packet', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['race_event_id'], ['race_events.id'], name=op.f('fk_race_signups_race_event_id_race_events')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_race_signups_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_race_signups'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('race_signups')
    op.drop_table('credit_card_infos')
    op.drop_table('users')
    op.drop_table('shopping_carts')
    op.drop_table('race_events')
    # ### end Alembic commands ###
