"""add race_cost

Revision ID: edcb4532d0a8
Revises: 7c02abea6af6
Create Date: 2024-02-14 13:10:24.807055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edcb4532d0a8'
down_revision = '7c02abea6af6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('race_cost', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_event', schema=None) as batch_op:
        batch_op.drop_column('race_cost')

    # ### end Alembic commands ###
