"""simplify raceSeSignup

Revision ID: eed83b02a337
Revises: 549b8516ab22
Create Date: 2024-03-04 11:52:36.923764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eed83b02a337'
down_revision = '549b8516ab22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_signups', schema=None) as batch_op:
        batch_op.drop_column('coupon_code')
        batch_op.drop_column('ship_packet')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_signups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ship_packet', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('coupon_code', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
